import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/hero'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (


    <div className={styles.container}>

      <Head>
        <title>Neuraltech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["bg-image"]}>
        <div className="container">
          <div className='topnav'>
            <a href="#servicios">Servicios</a>
            <a href="#productos">Productos</a>
            <a href="#certificaciones">Certificaciones</a>
            <a href="#sponsors">Sponsors</a>
            <a href="#contacto">Contacto</a>
          </div>
        </div>
      </div>

      <Hero />

    </div>
  )
}
