import Head from 'next/head'
import Hero from '../components/hero'
import Navbar from '../components/navbar'
import Footer from '../components/Footer'
import Clientes from '../components/Clientes'
import Certificaciones from '../components/Certificaciones'
import Contacto from '../components/Contacto'
import Servicios from '../components/Servicios'

export default function Home() {
  return (
    <>
      <Head>
        <title>Neuraltech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.jpeg" />
      </Head>

      <Navbar/>
      <Hero />
      <Servicios />
      <Clientes />
      <Certificaciones />
      <Contacto />
      <Footer />

    </>
  )
}
